version: '2'
services:
    mongodb:
        image: mongo:latest
        container_name: matmapa_mongodb

    postgres:
        image: postgres:latest
        container_name: matmapa_postgres

    node:
        build: .
        container_name: matmapa_node
        tty: true
        ports:
            - "80:3000"
        volumes:
            - <<<project_dir>>>:/matmapa
        links:
            - postgres:postgres
            - mongodb:mongodb
